---

- name: Copy Bika NGINX Config
  template:
    src: nginx.conf.j2
    dest: "{{ bika_nginx_conf }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
  tags: bika-nginx

- name: Copy Bika Administrative VHOST Config
  template:
    src: bika.conf.j2
    dest: "{{ bika_nginx_sites_available }}/bika.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
  tags: bika-nginx

- name: Copy Bika configured VHOSTS Config
  template:
    src: bika_vhosts.conf.j2
    dest: "{{ bika_nginx_sites_available }}/bika_vhosts.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
  tags: bika-nginx

- name: Enable Bika NGINX VHOST Configs
  shell: cd {{ bika_nginx_sites_enabled }} && ln -sf {{ bika_nginx_sites_available }}/bika* .
  notify:
    - reload nginx
  tags: bika-nginx

- name: Ensure Bika HTML Root
  file:
    path: "{{ bika_nginx_html_root }}"
    state: directory
  tags:
    - bika-nginx
    - bika-html

- name: Copy Bika HTML Files
  template:
    src: bika_control_panel.html.j2
    dest: "{{ bika_nginx_html_root }}/bika_control_panel.html"
  notify:
    - reload nginx
  tags:
    - bika-nginx
    - bika-html

- name: Remove default nginx vhost config file
  file:
    path: "{{ nginx_default_vhost_path }}"
    state: absent
  when: nginx_remove_default_vhost
  notify:
    - reload nginx
  tags:
    - bika-nginx

- name: Ensure NGINX is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
