---

- hosts: bika
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: Include Vagrant Variables `vagrant_configure.yml`
      include_vars: vagrant_configure.yml
      tags:
        - always

  roles:
    - role: bika
