---

# Bika specific NGINX configuration
bika_nginx_path: "/etc/nginx"
bika_nginx_html_root: "/usr/share/nginx/bika"
bika_nginx_sites_available: "{{ bika_nginx_path }}/sites-available"
bika_nginx_sites_enabled: "{{ bika_nginx_path }}/sites-enabled"
bika_nginx_conf: "{{ bika_nginx_path }}/nginx.conf"
bika_nginx_extra_http_options: |
  proxy_read_timeout 600s;

# VHOSTS
bika_vhosts: []
# Example:
#  - example.com
#  - test.example.com

# SSL
bika_ssl_certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem
bika_ssl_certificate_key: /etc/ssl/private/ssl-cert-snakeoil.key

# https://github.com/geerlingguy/ansible-role-nginx
nginx_remove_default_vhost: true
nginx_server_names_hash_bucket_size: "256"
nginx_client_max_body_size: "1024m"
